### ISSUE TITLE
Stm32 communicating with wiznet 7500 p

### ISSUE THREAD

**Issue by simogaspa84** [afiskon/stm32-w5500#1]
Hi @afiskon .. 

I have a stm32f429 mcu and wiznet 7500 p Programmed with the following sw 

https://docs.wiznet.io/Product/S2E-Module/WIZ750SR/download

Can i use your repo example to try to communicate with wiznet 7500 p? 

Thanks a lot

**Comment by afiskon** [comment]
You can, but the library was tested only with Wiznet W5500.
